In [1]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
import matplotlib

In [2]:
matplotlib.rcParams['font.sans-serif'] = ['KaiTi']

In [4]:
filename = 'big_data/all_emotion_songs.json'
with open(filename, 'r', encoding='utf-8') as fr:       
    all_emotion_songs = json.load(fp=fr)

In [5]:
all_emotion_songs[1]

{'_id': 34509586, 'tags': ['华语', '综艺', '摇滚', '温柔']}

# 评分选取

In [6]:
def tanh(x):
    return np.sinh(x)/np.cosh(x)

In [20]:
def Sigmoid(x):
    return 1. / (1 + np.exp(-x))

In [19]:
tanh(-0.1)

-0.09966799462495583

In [23]:
Sigmoid(-1.8)

0.14185106490048777

In [24]:
filename = 'big_data/all_ratting.json'
with open(filename, 'r', encoding='utf-8') as fr:       
    all_ratting = json.load(fp=fr)

In [41]:
test_list = random.sample(all_ratting, 400)

In [43]:
df_test = pd.DataFrame(test_list, columns=['uid', 'sid', 'subscribedCount', 'playCount'])

In [44]:
df_test

            uid         sid  subscribedCount  playCount
0    2651681933    32358759             1806      39755
1    2033140070  1450065506            27128     750815
2    3227947470  1446865301                5       2060
3    5113374150  1419346842               15        544
4    2483045398    21799580             2469     117061
..          ...         ...              ...        ...
395   701079828   553402636               12       7894
396   996354372     3204385               31       2648
397  2224212377      108224             1298     167192
398   870859672    41643321             8694     644429
399   717442460    31789010              491      47324

[400 rows x 4 columns]

In [45]:
df_test['total'] = df_test['subscribedCount'] * 55 + df_test['playCount']

In [46]:
df_test

            uid         sid  subscribedCount  playCount    total
0    2651681933    32358759             1806      39755   139085
1    2033140070  1450065506            27128     750815  2242855
2    3227947470  1446865301                5       2060     2335
3    5113374150  1419346842               15        544     1369
4    2483045398    21799580             2469     117061   252856
..          ...         ...              ...        ...      ...
395   701079828   553402636               12       7894     8554
396   996354372     3204385               31       2648     4353
397  2224212377      108224             1298     167192   238582
398   870859672    41643321             8694     644429  1122599
399   717442460    31789010              491      47324    74329

[400 rows x 5 columns]

In [49]:
total_min = df_test.total.min()
total_max = df_test.total.max()
total_s = total_max - total_min

In [50]:
total_s

56889329

计算最值归一化

In [51]:
df_test['extream_normal'] = (df_test['total'] - total_min) / (total_s)

计算均方差归一化

In [54]:
total_mean = df_test.total.mean()
total_std = df_test.total.std()

In [55]:
total_mean

1106952.9025

In [56]:
total_std

3925924.8776392764

In [57]:
df_test['std_normal'] = (df_test['total'] - total_mean) / (total_std)

In [58]:
df_test

,uid,sid,subscribedCount,playCount,total,extream_normal,std_normal
0,2651681933,32358759,1806,39755,139085,0.002445,-0.246532
1,2033140070,1450065506,27128,750815,2242855,0.039425,0.289334
2,3227947470,1446865301,5,2060,2335,0.000041,-0.281365
3,5113374150,1419346842,15,544,1369,0.000024,-0.281611
4,2483045398,21799580,2469,117061,252856,0.004445,-0.217553
...,...,...,...,...,...,...,...
395,701079828,553402636,12,7894,8554,0.000150,-0.279781
396,996354372,3204385,31,2648,4353,0.000076,-0.280851
397,2224212377,108224,1298,167192,238582,0.004194,-0.221189
398,870859672,41643321,8694,644429,1122599,0.019733,0.003985
399,717442460,31789010,491,47324,74329,0.001306,-0.263027

In [66]:
df_test['tanh_extream'] = df_test['extream_normal'].map(Sigmoid)

In [67]:
df_test

,uid,sid,subscribedCount,playCount,total,extream_normal,std_normal,tanh_extream
0,2651681933,32358759,1806,39755,139085,0.002445,-0.246532,0.500611
1,2033140070,1450065506,27128,750815,2242855,0.039425,0.289334,0.509855
2,3227947470,1446865301,5,2060,2335,0.000041,-0.281365,0.500010
3,5113374150,1419346842,15,544,1369,0.000024,-0.281611,0.500006
4,2483045398,21799580,2469,117061,252856,0.004445,-0.217553,0.501111
...,...,...,...,...,...,...,...,...
395,701079828,553402636,12,7894,8554,0.000150,-0.279781,0.500038
396,996354372,3204385,31,2648,4353,0.000076,-0.280851,0.500019
397,2224212377,108224,1298,167192,238582,0.004194,-0.221189,0.501048
398,870859672,41643321,8694,644429,1122599,0.019733,0.003985,0.504933
399,717442460,31789010,491,47324,74329,0.001306,-0.263027,0.500327

In [69]:
Sigmoid(0.039425)

0.5098549735424681

In [70]:
df_test.rename(columns={'extream_normal': 'extreme_normal'}, inplace=True)

In [71]:
df_test.rename(columns={'tanh_extream': 'tanh_extreme'}, inplace=True)

In [72]:
df_test

,uid,sid,subscribedCount,playCount,total,extreme_normal,std_normal,tanh_extreme
0,2651681933,32358759,1806,39755,139085,0.002445,-0.246532,0.500611
1,2033140070,1450065506,27128,750815,2242855,0.039425,0.289334,0.509855
2,3227947470,1446865301,5,2060,2335,0.000041,-0.281365,0.500010
3,5113374150,1419346842,15,544,1369,0.000024,-0.281611,0.500006
4,2483045398,21799580,2469,117061,252856,0.004445,-0.217553,0.501111
...,...,...,...,...,...,...,...,...
395,701079828,553402636,12,7894,8554,0.000150,-0.279781,0.500038
396,996354372,3204385,31,2648,4353,0.000076,-0.280851,0.500019
397,2224212377,108224,1298,167192,238582,0.004194,-0.221189,0.501048
398,870859672,41643321,8694,644429,1122599,0.019733,0.003985,0.504933
399,717442460,31789010,491,47324,74329,0.001306,-0.263027,0.500327

In [74]:
df_test['tanh_extreme'] = df_test['extreme_normal'].map(tanh)

In [75]:
df_test

,uid,sid,subscribedCount,playCount,total,extreme_normal,std_normal,tanh_extreme
0,2651681933,32358759,1806,39755,139085,0.002445,-0.246532,0.002445
1,2033140070,1450065506,27128,750815,2242855,0.039425,0.289334,0.039404
2,3227947470,1446865301,5,2060,2335,0.000041,-0.281365,0.000041
3,5113374150,1419346842,15,544,1369,0.000024,-0.281611,0.000024
4,2483045398,21799580,2469,117061,252856,0.004445,-0.217553,0.004445
...,...,...,...,...,...,...,...,...
395,701079828,553402636,12,7894,8554,0.000150,-0.279781,0.000150
396,996354372,3204385,31,2648,4353,0.000076,-0.280851,0.000076
397,2224212377,108224,1298,167192,238582,0.004194,-0.221189,0.004194
398,870859672,41643321,8694,644429,1122599,0.019733,0.003985,0.019730
399,717442460,31789010,491,47324,74329,0.001306,-0.263027,0.001306

In [77]:
tanh(0.039425	)

0.03940458619686228

In [78]:
df_test['sigmoid_std'] = df_test['std_normal'].map(Sigmoid)

In [79]:
df_test

,uid,sid,subscribedCount,playCount,total,extreme_normal,std_normal,tanh_extreme,sigmoid_std
0,2651681933,32358759,1806,39755,139085,0.002445,-0.246532,0.002445,0.438677
1,2033140070,1450065506,27128,750815,2242855,0.039425,0.289334,0.039404,0.571833
2,3227947470,1446865301,5,2060,2335,0.000041,-0.281365,0.000041,0.430119
3,5113374150,1419346842,15,544,1369,0.000024,-0.281611,0.000024,0.430059
4,2483045398,21799580,2469,117061,252856,0.004445,-0.217553,0.004445,0.445825
...,...,...,...,...,...,...,...,...,...
395,701079828,553402636,12,7894,8554,0.000150,-0.279781,0.000150,0.430507
396,996354372,3204385,31,2648,4353,0.000076,-0.280851,0.000076,0.430245
397,2224212377,108224,1298,167192,238582,0.004194,-0.221189,0.004194,0.444927
398,870859672,41643321,8694,644429,1122599,0.019733,0.003985,0.019730,0.500996
399,717442460,31789010,491,47324,74329,0.001306,-0.263027,0.001306,0.434620

In [82]:
df_test['marking'] = df_test['sigmoid_std'].map(lambda x: round(x * 10, 2))

In [83]:
df_test

,uid,sid,subscribedCount,playCount,total,extreme_normal,std_normal,tanh_extreme,sigmoid_std,marking
0,2651681933,32358759,1806,39755,139085,0.002445,-0.246532,0.002445,0.438677,4.39
1,2033140070,1450065506,27128,750815,2242855,0.039425,0.289334,0.039404,0.571833,5.72
2,3227947470,1446865301,5,2060,2335,0.000041,-0.281365,0.000041,0.430119,4.30
3,5113374150,1419346842,15,544,1369,0.000024,-0.281611,0.000024,0.430059,4.30
4,2483045398,21799580,2469,117061,252856,0.004445,-0.217553,0.004445,0.445825,4.46
...,...,...,...,...,...,...,...,...,...,...
395,701079828,553402636,12,7894,8554,0.000150,-0.279781,0.000150,0.430507,4.31
396,996354372,3204385,31,2648,4353,0.000076,-0.280851,0.000076,0.430245,4.30
397,2224212377,108224,1298,167192,238582,0.004194,-0.221189,0.004194,0.444927,4.45
398,870859672,41643321,8694,644429,1122599,0.019733,0.003985,0.019730,0.500996,5.01
399,717442460,31789010,491,47324,74329,0.001306,-0.263027,0.001306,0.434620,4.35

选取需要的列

In [88]:
df_test_marking = df_test.loc[:, ['uid', 'sid', 'marking']]

In [89]:
df_test_marking

            uid         sid  marking
0    2651681933    32358759     4.39
1    2033140070  1450065506     5.72
2    3227947470  1446865301     4.30
3    5113374150  1419346842     4.30
4    2483045398    21799580     4.46
..          ...         ...      ...
395   701079828   553402636     4.31
396   996354372     3204385     4.30
397  2224212377      108224     4.45
398   870859672    41643321     5.01
399   717442460    31789010     4.35

[400 rows x 3 columns]

In [90]:
df_test_marking.marking.min()

4.3

In [91]:
df_test_marking.marking.max()

10.0

In [93]:
group_df = df_test_marking.groupby(by='sid')

In [96]:
for key, value in group_df:
    print(value)

           uid    sid  marking
350  786144335  64550     5.65
            uid    sid  marking
271  3048346625  65538     4.35
           uid    sid  marking
84  2775096678  66532     4.31
           uid    sid  marking
62  2072866745  67873      5.3
           uid    sid  marking
33  2190534648  87949     4.43
            uid    sid  marking
261  2894416520  89125     4.33
            uid     sid  marking
318  2206206696  104307     4.44
            uid     sid  marking
397  2224212377  108224     4.45
            uid     sid  marking
196  5058126656  108461      4.3
           uid     sid  marking
239  470487642  109915      4.6
           uid     sid  marking
103  166397998  111536     9.57
            uid     sid  marking
175  5256288755  139227      4.3
            uid     sid  marking
365  3018506236  139774     4.38
            uid     sid  marking
247  2113373295  147258     4.42
          uid     sid  marking
14  585321268  158338     4.36
            uid     sid  marking
298  4995920068  158891      4.3
           uid     sid  marking
320  381584446  167858     4.71
          uid     sid  marking
79  386501538  186001     5.38
           uid     sid  marking
369  945507741  186453     5.04
           uid     sid  marking
339  147825578  190808     7.41
           uid     sid  marking
355  972738648  201768     4.78
            uid     sid  marking
220  1993039994  210062      8.4
            uid     sid  marking
359  2716696426  212233      4.3
          uid     sid  marking
335  68720536  225894     4.36
            uid     sid  marking
317  2971975766  234064     4.41
            uid     sid  marking
228  2753622499  259193     5.58
            uid     sid  marking
312  2160479853  279620     4.37
            uid     sid  marking
195  2117448109  320402      4.8
            uid     sid  marking
258  5352566036  330584     4.34
           uid     sid  marking
176  692426379  332669      4.6
            uid     sid  marking
125  2963335181  343977     4.39
            uid     sid  marking
360  4911823067  370472      4.3
            uid     sid  marking
207  2360731906  375119     4.33
            uid     sid  marking
343  2762547172  393514     4.56
            uid     sid  marking
366  5096130096  394990      4.3
            uid     sid  marking
305  5394891394  395159      4.3
           uid     sid  marking
25  2396846909  425620     4.33
            uid     sid  marking
265  2097801896  460605      4.7
            uid     sid  marking
294  2668218460  469197     4.36
            uid     sid  marking
218  2937582243  519025     4.37
           uid     sid  marking
384  775165791  522572     4.98
           uid     sid  marking
41  2460667930  534343     4.36
            uid     sid  marking
126  2937582243  542104     4.37
           uid     sid  marking
67  2543003428  584155     4.97
           uid     sid  marking
373  994075756  731783     4.37
           uid     sid  marking
314  109346819  740223     4.41
            uid     sid  marking
285  2633853235  760058      4.4
           uid     sid  marking
12  5102247603  812400     4.31
           uid     sid  marking
229  927010098  848415     5.74
          uid     sid  marking
22  917485767  868690     4.32
            uid     sid  marking
226  2159690690  873013     4.32
           uid      sid  marking
107  586539609  1059911     4.31
            uid      sid  marking
188  4988242505  1070865     4.43
           uid      sid  marking
283  865653486  1140054     4.47
         uid      sid  marking
322  6842364  1156724     4.37
            uid      sid  marking
375  2469688795  1682830     4.38
          uid      sid  marking
148  29622426  1714503     4.45
            uid      sid  marking
141  5123838271  2112993     4.31
            uid      sid  marking
238  2111203675  2215668      4.3
            uid      sid  marking
370  5036844459  2309623      4.3
            uid      sid  marking
342  2552840679  2614003     4.81
            uid      sid  marking
253  4901511925  2933442     7.95
           uid      sid  marking
396  996354372  3204385      4.3
            uid      sid  marking
284  2973656224  3545889     4.31
          uid      sid  marking
45  744145413  3819561     4.95
          uid      sid  marking
316  74200261  4347260     4.49
            uid      sid  marking
179  5382545128  4354392      4.3
            uid      sid  marking
139  4895865124  4436116     4.33
            uid      sid  marking
199  2223141344  4437987     4.37
           uid      sid  marking
142  580641691  4440230     4.36
            uid      sid  marking
306  5075537814  4472316      4.3
          uid      sid  marking
165  44623414  4872566     4.36
            uid      sid  marking
272  4919253383  4876705      4.3
           uid      sid  marking
394  425677420  5138206     4.38
            uid      sid  marking
323  4939222626  5165368      4.3
           uid      sid  marking
159  736034992  5175490     4.43
          uid      sid  marking
143  25649466  5188765     4.45
            uid      sid  marking
158  5377490292  5247677      4.3
            uid      sid  marking
221  2248621112  5264814     4.65
            uid      sid  marking
230  2252789241  5266866     4.48
            uid      sid  marking
256  5114402466  5268324     4.41
            uid       sid  marking
393  2674683266  16434100      4.4
           uid       sid  marking
381  564118068  16574203      4.3
          uid       sid  marking
249  89963967  16866735     8.08
           uid       sid  marking
18  2205014977  16959121     4.36
            uid       sid  marking
262  2125946958  17139867      4.3
            uid       sid  marking
251  5381460857  17290782      4.3
            uid       sid  marking
242  2667641834  17417067     7.29
          uid       sid  marking
138  10455152  17449087     4.38
           uid       sid  marking
39  2125946958  17990105      4.3
         uid       sid  marking
43  71529766  18208053      4.3
           uid       sid  marking
28  5366387176  18291344      4.3
            uid       sid  marking
240  4901511925  18605579     7.95
          uid       sid  marking
56  651754759  18943535     4.36
            uid       sid  marking
349  2042401123  20120449     4.31
           uid       sid  marking
347  311179211  21257314     7.35
           uid       sid  marking
100  943546500  21724168     4.32
          uid       sid  marking
4  2483045398  21799580     4.46
         uid       sid  marking
364  9777434  21936958     4.32
            uid       sid  marking
255  5063746222  22478093      4.3
          uid       sid  marking
367  96296637  22598710     4.33
            uid       sid  marking
290  1995538813  22627407     8.78
          uid       sid  marking
124  52924044  22675077     4.31
           uid       sid  marking
60  5308818385  22736274      4.3
          uid       sid  marking
77  879558884  23747599     4.33
          uid       sid  marking
70  923109695  25643361     4.88
            uid       sid  marking
224  2248621112  26090063     4.65
          uid       sid  marking
63  400926214  26107913     4.42
            uid       sid  marking
186  4944138426  26114654     7.81
          uid       sid  marking
160  83959866  26241456     4.42
          uid       sid  marking
44  779452086  26468752     4.87
          uid       sid  marking
23  399443851  27588486     9.69
          uid       sid  marking
34  436318360  27672026     4.51
           uid       sid  marking
177  720987277  27787716      4.3
            uid       sid  marking
132  2494551564  27858756     4.44
           uid       sid  marking
120  640904299  27874945     4.57
          uid       sid  marking
267  56969941  27894199     5.89
           uid       sid  marking
88  2055985930  27907863     4.34
           uid       sid  marking
389  732346026  27970126     5.21
           uid       sid  marking
115  360578685  28002610     4.87
          uid       sid  marking
59  138839303  28029525     6.85
           uid       sid  marking
156  769556264  28253609     5.22
            uid       sid  marking
109  2805822163  28387625     4.72
            uid       sid  marking
309  2766603456  28461702     4.69
           uid       sid  marking
32  2283674234  28508181     4.31
            uid       sid  marking
205  2047661253  28508449     8.21
            uid       sid  marking
202  5004811487  28509655      4.3
            uid       sid  marking
222  5089760418  28510669     4.37
           uid       sid  marking
17  4895865124  28511280     4.33
         uid       sid  marking
7  728712123  28549169      4.3
           uid       sid  marking
38  2454997531  28563201     4.77
           uid       sid  marking
114  156593025  28686698     4.42
            uid       sid  marking
134  2611618759  28700286     4.31
            uid       sid  marking
269  4913440902  28718076     4.36
            uid       sid  marking
231  2210734465  28855797      4.3
            uid       sid  marking
257  2024518101  28864449     10.0
            uid       sid  marking
368  2292140557  29137871     9.97
           uid       sid  marking
348  968035361  29137872     4.47
            uid       sid  marking
184  2837650335  29452826     4.32
          uid       sid  marking
98  882128375  29498556      4.3
         uid       sid  marking
86  25649466  29544386     4.45
           uid       sid  marking
72  5063968392  29553031      4.3
           uid       sid  marking
385  169026194  29569226     5.53
            uid       sid  marking
310  2652485497  29722815      4.6
            uid       sid  marking
217  2769304531  29732659     4.79
           uid       sid  marking
234  812597648  29759543     4.47
            uid       sid  marking
105  2812015367  29789260      4.6
            uid       sid  marking
383  2838690323  29793230      4.3
           uid       sid  marking
69  2048533998  29796098     4.42
           uid       sid  marking
50  2800133178  29797698     4.32
           uid       sid  marking
197  382282229  29811108     4.45
            uid       sid  marking
172  1979792716  30039393     4.52
            uid       sid  marking
250  2334345226  30070844     6.92
           uid       sid  marking
376  691363165  30260095     4.44
            uid       sid  marking
292  2392222655  30398306     7.27
          uid       sid  marking
146  56758190  30903196     6.52
            uid       sid  marking
287  5083087535  31090875      4.3
           uid       sid  marking
227  653165514  31245090     4.36
          uid       sid  marking
297  91068376  31311622     4.54
           uid       sid  marking
399  717442460  31789010     4.35
            uid       sid  marking
204  2670149975  31838398     4.45
           uid       sid  marking
52  2611211695  32038810     4.38
            uid       sid  marking
387  1982971724  32102375     4.33
          uid       sid  marking
0  2651681933  32358759     4.39
            uid       sid  marking
149  3210445148  32574975      4.3
           uid       sid  marking
51  2646995337  32619105     4.31
           uid       sid  marking
37  2140284574  32712542     6.43
           uid       sid  marking
29  5186199701  32835004      4.3
            uid       sid  marking
254  5335917846  33223316      4.3
            uid       sid  marking
153  2040908111  33233922     4.65
           uid       sid  marking
324  626681184  33367334     4.33
           uid       sid  marking
80  2249569042  33556030     4.32
            uid       sid  marking
212  3014052871  33699628     4.31
            uid       sid  marking
241  2966084086  34033274     4.31
            uid       sid  marking
328  4979281819  34179036      4.3
           uid       sid  marking
190  429548214  34274367     7.81
           uid       sid  marking
81  2128181001  34779256     4.32
           uid       sid  marking
137  461433402  35090883     4.52
            uid       sid  marking
236  2267672286  36924301     6.69
            uid       sid  marking
337  2437087776  37155486     4.31
           uid       sid  marking
260  579948016  38019293     4.49
            uid       sid  marking
101  5382531313  38358820      4.3
           uid       sid  marking
96  5322668716  39449194      4.3
            uid       sid  marking
333  1987910427  40140643     4.33
           uid       sid  marking
398  870859672  41643321     5.01
            uid       sid  marking
203  2225340997  41651113     4.49
            uid       sid  marking
280  2618496187  41657124     4.33
            uid        sid  marking
118  2192251029  401249224     4.52
            uid        sid  marking
215  2244648436  402172275     4.35
          uid        sid  marking
87  818294738  406407222      4.3
            uid        sid  marking
374  2546841127  410710410      4.6
          uid        sid  marking
53  603594393  411349737     4.32
           uid        sid  marking
219  136165772  412187871     4.31
           uid        sid  marking
344  875732045  413077048     6.79
          uid        sid  marking
85  467608936  413188696      4.6
           uid        sid  marking
259  366338082  417250937     4.59
            uid        sid  marking
128  2401666281  417859391     4.59
            uid        sid  marking
281  2388932132  419250418     4.46
            uid        sid  marking
391  2667410635  421269927      4.3
           uid        sid  marking
58  2953845455  423228325      4.3
            uid        sid  marking
245  5256832589  425828384      4.3
           uid        sid  marking
16  2201932475  426027293     4.31
          uid        sid  marking
76  597593834  426881103     4.52
           uid        sid  marking
49  2893791256  430026599      4.3
            uid        sid  marking
178  4999633913  435289349     4.37
            uid        sid  marking
263  2613174914  436668736     4.31
            uid        sid  marking
353  5288700864  439665755      4.3
           uid        sid  marking
54  5378471509  441437222      4.3
           uid        sid  marking
46  2666549476  442589034     4.31
            uid        sid  marking
270  4928562007  445238181      4.3
            uid        sid  marking
192  2283364573  448518438     4.53
            uid        sid  marking
174  4898400392  448917631     4.32
            uid        sid  marking
147  2228877085  450224780     4.31
          uid        sid  marking
61  766857846  454053869      4.3
           uid        sid  marking
311  509020206  454224994      6.4
           uid        sid  marking
246  769525238  454930083     4.32
            uid        sid  marking
377  2270895603  456175630      4.3
            uid        sid  marking
321  2559201080  456381024      4.3
           uid        sid  marking
216  938187173  456822251     4.52
            uid        sid  marking
331  2038547763  459004763     4.87
            uid        sid  marking
378  2811412603  460514780     4.31
            uid        sid  marking
182  2388932132  461581072     4.46
            uid        sid  marking
382  4956024956  463473758      4.3
            uid        sid  marking
112  2705576196  465780707     4.37
            uid        sid  marking
354  2475774732  466333783     4.47
            uid        sid  marking
301  2370737080  467590255     4.31
           uid        sid  marking
336  310230899  468513168      4.4
            uid        sid  marking
110  2741315133  468819252     4.35
            uid        sid  marking
288  2130180378  472385776     7.91
            uid        sid  marking
155  2439439036  473940085     5.51
            uid        sid  marking
313  4976342299  479219423      4.3
            uid        sid  marking
135  2775499672  479325937     4.35
            uid        sid  marking
133  5213242418  479717618      4.3
           uid        sid  marking
145  598898618  479938716     4.58
            uid        sid  marking
225  2083762616  480575050      4.3
           uid        sid  marking
106  874523523  480648649      4.3
            uid        sid  marking
108  5026408261  482085921      4.3
          uid        sid  marking
83  467608936  482256911      4.6
          uid        sid  marking
6  2638142102  487527984     9.01
            uid        sid  marking
252  2245879076  489606010     4.48
          uid        sid  marking
361  33263537  490381792     4.55
            uid        sid  marking
169  2275461582  491294092     4.35
         uid        sid  marking
8  918864074  493041563     4.49
            uid        sid  marking
380  2415911767  503207480      4.3
            uid        sid  marking
144  4998412031  504748142     4.35
           uid        sid  marking
95  2275721310  507114221     4.36
            uid        sid  marking
119  2825954136  507134193     4.31
          uid        sid  marking
97  572989866  513704704     4.53
            uid        sid  marking
198  2681126643  513797368     4.31
           uid        sid  marking
31  2766667231  519112175      4.3
            uid        sid  marking
372  2808091868  520566118     4.32
            uid        sid  marking
183  2103475073  520566357     4.87
            uid        sid  marking
223  2103475073  520567622     4.87
            uid        sid  marking
201  5390665690  521526314      4.3
            uid        sid  marking
206  2807134275  523574080      4.3
            uid        sid  marking
191  3032241524  525112224     4.32
            uid        sid  marking
154  2612294051  525239752     4.32
            uid        sid  marking
293  2456346520  527335918     7.05
           uid        sid  marking
235  888011144  528271077     9.32
           uid        sid  marking
90  2948136603  530412216     4.33
            uid        sid  marking
163  2310101021  533375020      4.3
           uid        sid  marking
371  505085564  541511427     4.35
          uid        sid  marking
13  416785134  545215204     4.57
           uid        sid  marking
395  701079828  553402636     4.31
            uid        sid  marking
302  2060923262  555435319     4.38
           uid        sid  marking
24  2087552342  557236489      4.9
            uid        sid  marking
213  2475901211  569214126     8.16
345  5329802595  569214126     4.35
            uid        sid  marking
338  2483920865  571336838     4.57
           uid        sid  marking
30  2076008495  572848663     4.35
            uid        sid  marking
232  2958483562  573428444      5.6
            uid        sid  marking
291  2851240533  573617587     4.53
           uid        sid  marking
116  817832348  574926602     6.23
            uid        sid  marking
102  2586428019  864267668      4.3
           uid        sid  marking
21  3087729449  865048105     5.07
          uid        sid  marking
15  709875054  865592685      4.3
            uid         sid  marking
277  2837186301  1299563521     4.66
            uid         sid  marking
356  5052577162  1299563528      4.3
            uid         sid  marking
278  2028982493  1299844315     4.41
            uid         sid  marking
123  2342190588  1300452341      4.3
           uid         sid  marking
92  2414682190  1301441430     4.48
           uid         sid  marking
99  2289361714  1301861948     4.44
            uid         sid  marking
161  2337912688  1302096636     5.36
            uid         sid  marking
170  2397251560  1304716261     4.41
          uid         sid  marking
5  2595906581  1305366002     4.45
            uid         sid  marking
208  2661427889  1306234059     4.31
            uid         sid  marking
299  2608012368  1306496090     4.33
            uid         sid  marking
264  2211857196  1306497271     4.42
            uid         sid  marking
303  2427060544  1306497795     5.03
            uid         sid  marking
164  2741288736  1306923998     4.31
           uid         sid  marking
104  896047084  1309321064     9.96
            uid         sid  marking
131  4880317936  1314680630      4.3

一首歌会被多个用户评分，但这里使用歌单模拟用户，最终的评分也是依据这首歌所在歌单的订阅数与播放数计算而来，因此不能采用通常的平均得分来决定这首歌的质量

In [97]:
print('as')

as